const enginesData = [
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67303",
    product_id: 67303,
    title: "Двигатель",
    make: "Volvo",
    model: "Xc60",
    year: null,
    engine_code: "B4204T7",
    engine_type: "unknown",
    price: 75000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176648217756_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67301",
    product_id: 67301,
    title: "Двигатель",
    make: "Honda",
    model: "Element",
    year: null,
    engine_code: "K24A4",
    engine_type: "unknown",
    price: 100000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176648187046_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67299",
    product_id: 67299,
    title: "Двигатель",
    make: "Honda",
    model: "Element",
    year: null,
    engine_code: "K24A4",
    engine_type: "unknown",
    price: 100000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176648160481_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67297",
    product_id: 67297,
    title: "Двигатель",
    make: "Honda",
    model: "Element",
    year: null,
    engine_code: "K24A8",
    engine_type: "unknown",
    price: 80000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176648115589_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67295",
    product_id: 67295,
    title: "Двигатель",
    make: "Honda",
    model: "Element",
    year: null,
    engine_code: "K24A8",
    engine_type: "unknown",
    price: 80000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176648063813_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67293",
    product_id: 67293,
    title: "Двигатель",
    make: "Honda",
    model: "Civic",
    year: null,
    engine_code: "R18A1",
    engine_type: "unknown",
    price: 50000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176648017197_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67291",
    product_id: 67291,
    title: "Двигатель",
    make: "Honda",
    model: "Civic",
    year: null,
    engine_code: "R18A1",
    engine_type: "unknown",
    price: 50000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176647957136_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67289",
    product_id: 67289,
    title: "Двигатель",
    make: "Honda",
    model: "Civic",
    year: null,
    engine_code: "R18A1",
    engine_type: "unknown",
    price: 50000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176647912313_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67287",
    product_id: 67287,
    title: "Двигатель",
    make: "Honda",
    model: "CR-V",
    year: null,
    engine_code: "R20A1",
    engine_type: "unknown",
    price: 50000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176647366710_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67285",
    product_id: 67285,
    title: "Двигатель",
    make: "Honda",
    model: "CR-V",
    year: null,
    engine_code: "R20A1",
    engine_type: "unknown",
    price: 50000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176647306643_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67283",
    product_id: 67283,
    title: "Двигатель",
    make: "Honda",
    model: "CR-V",
    year: null,
    engine_code: "R20A1",
    engine_type: "unknown",
    price: 50000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/17664726839_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67281",
    product_id: 67281,
    title: "Двигатель",
    make: "Honda",
    model: "CR-V",
    year: null,
    engine_code: "K24Z1",
    engine_type: "unknown",
    price: 80000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176647164459_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67279",
    product_id: 67279,
    title: "Двигатель",
    make: "Honda",
    model: "CR-V",
    year: null,
    engine_code: "K24Z1",
    engine_type: "unknown",
    price: 80000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/17664711950_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67277",
    product_id: 67277,
    title: "Двигатель",
    make: "Honda",
    model: "Accord",
    year: null,
    engine_code: "R20A3",
    engine_type: "unknown",
    price: 100000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176647029730_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67275",
    product_id: 67275,
    title: "Двигатель",
    make: "Honda",
    model: "Accord",
    year: null,
    engine_code: "R20A3",
    engine_type: "unknown",
    price: 100000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176646969584_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67272",
    product_id: 67272,
    title: "Двигатель",
    make: "Chevrolet",
    model: "Aveo",
    year: null,
    engine_code: "L95",
    engine_type: "unknown",
    price: 70000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176646709386_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67270",
    product_id: 67270,
    title: "Двигатель",
    make: "Chevrolet",
    model: "Aveo",
    year: null,
    engine_code: "LMU",
    engine_type: "unknown",
    price: 70000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "93736684",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176646529968_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67268",
    product_id: 67268,
    title: "Двигатель",
    make: "Chevrolet",
    model: "Aveo",
    year: null,
    engine_code: "LMU",
    engine_type: "unknown",
    price: 70000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "93736684",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176646478929_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67266",
    product_id: 67266,
    title: "Двигатель",
    make: "Volkswagen",
    model: "Polo",
    year: null,
    engine_code: "CLSA",
    engine_type: "unknown",
    price: 80000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "03C100038G",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176646323860_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67264",
    product_id: 67264,
    title: "Двигатель",
    make: "Volkswagen",
    model: "Jetta",
    year: null,
    engine_code: "CFNA",
    engine_type: "unknown",
    price: 80000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "03C100038H",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176646297582_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67262",
    product_id: 67262,
    title: "Двигатель",
    make: "Volkswagen",
    model: "Jetta",
    year: null,
    engine_code: "CFNA",
    engine_type: "unknown",
    price: 80000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "03C100038H",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176645995734_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67260",
    product_id: 67260,
    title: "Двигатель",
    make: "Volkswagen",
    model: "Jetta",
    year: null,
    engine_code: "CFNA",
    engine_type: "unknown",
    price: 80000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "03C100038H",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176645837128_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67258",
    product_id: 67258,
    title: "Двигатель",
    make: "Geely",
    model: "Coolray",
    year: null,
    engine_code: "JLH-3G15TD",
    engine_type: "unknown",
    price: 200000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/17664565017_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67256",
    product_id: 67256,
    title: "Двигатель",
    make: "Haval",
    model: "H6",
    year: null,
    engine_code: "GW4G15B",
    engine_type: "unknown",
    price: 80000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176645606253_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67249",
    product_id: 67249,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla",
    year: null,
    engine_code: "1ZR-FE",
    engine_type: "unknown",
    price: 110000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "190000T030",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176641329443_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67247",
    product_id: 67247,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla",
    year: null,
    engine_code: "1ZZ-FE",
    engine_type: "unknown",
    price: 120000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "1900022A40",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176641208697_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67245",
    product_id: 67245,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla",
    year: null,
    engine_code: "1ZZ-FE",
    engine_type: "unknown",
    price: 120000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "1900022330",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176641187944_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67243",
    product_id: 67243,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla",
    year: null,
    engine_code: "1ZZ-FE",
    engine_type: "unknown",
    price: 120000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "170000D820",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176641156323_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67241",
    product_id: 67241,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla",
    year: null,
    engine_code: "1ZZ-FE",
    engine_type: "unknown",
    price: 120000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "170000D820",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176641125440_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67239",
    product_id: 67239,
    title: "Двигатель",
    make: "Audi",
    model: "A6",
    year: null,
    engine_code: "BPJ",
    engine_type: "unknown",
    price: 120000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "06D100033H",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176641092046_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67237",
    product_id: 67237,
    title: "Двигатель",
    make: "Audi",
    model: "A6",
    year: null,
    engine_code: "BDW",
    engine_type: "unknown",
    price: 115000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "000100020AH",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176641077158_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67235",
    product_id: 67235,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "ASX",
    year: null,
    engine_code: "4A92",
    engine_type: "unknown",
    price: 90000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/17664105164_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67233",
    product_id: 67233,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "ASX",
    year: null,
    engine_code: "4A92",
    engine_type: "unknown",
    price: 90000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176641036622_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67231",
    product_id: 67231,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "Lancer",
    year: null,
    engine_code: "4A91",
    engine_type: "unknown",
    price: 50000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176641019298_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67229",
    product_id: 67229,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "Lancer",
    year: null,
    engine_code: "4A91",
    engine_type: "unknown",
    price: 50000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176641005942_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67227",
    product_id: 67227,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla",
    year: null,
    engine_code: "1ZZ-FE",
    engine_type: "unknown",
    price: 120000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "170000D820",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/17664098281_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67225",
    product_id: 67225,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "Lancer",
    year: null,
    engine_code: "4A91",
    engine_type: "unknown",
    price: 50000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640952733_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67223",
    product_id: 67223,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "Outlander",
    year: null,
    engine_code: "4B12",
    engine_type: "unknown",
    price: 75000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "1000A945, 1000C854",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/17664093611_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67221",
    product_id: 67221,
    title: "Двигатель",
    make: "Audi",
    model: "A6",
    year: null,
    engine_code: "BDW",
    engine_type: "unknown",
    price: 115000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640897540_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67219",
    product_id: 67219,
    title: "Двигатель",
    make: "Nissan",
    model: "Note",
    year: null,
    engine_code: "HR16DE",
    engine_type: "unknown",
    price: 40000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "10102CJ00F",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640871433_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67217",
    product_id: 67217,
    title: "Двигатель",
    make: "Nissan",
    model: "Note",
    year: null,
    engine_code: "HR16DE",
    engine_type: "unknown",
    price: 40000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "10102CJ00F",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640837292_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67215",
    product_id: 67215,
    title: "Двигатель",
    make: "Nissan",
    model: "Note",
    year: null,
    engine_code: "HR16DE",
    engine_type: "unknown",
    price: 40000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "10102CJ00F",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640813235_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67213",
    product_id: 67213,
    title: "Двигатель",
    make: "Nissan",
    model: "Teana",
    year: null,
    engine_code: "VQ25DE",
    engine_type: "unknown",
    price: 35000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "10102JN0AW",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640766613_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67211",
    product_id: 67211,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "Galant Fortis",
    year: null,
    engine_code: "4B10",
    engine_type: "unknown",
    price: 100000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640740377_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67209",
    product_id: 67209,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "Lancer",
    year: null,
    engine_code: "4B10",
    engine_type: "unknown",
    price: 100000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640699130_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67207",
    product_id: 67207,
    title: "Двигатель",
    make: "Nissan",
    model: "Note",
    year: null,
    engine_code: "HR16DE",
    engine_type: "unknown",
    price: 40000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "10102CJ00F",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640662688_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67205",
    product_id: 67205,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "ASX",
    year: null,
    engine_code: "4A92",
    engine_type: "unknown",
    price: 90000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640627752_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67203",
    product_id: 67203,
    title: "Двигатель",
    make: "Toyota",
    model: "RAV4",
    year: null,
    engine_code: "2AZ-FE",
    engine_type: "unknown",
    price: 100000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "190000H132",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640606045_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67201",
    product_id: 67201,
    title: "Двигатель",
    make: "Audi",
    model: "A6",
    year: null,
    engine_code: "BDW",
    engine_type: "unknown",
    price: 115000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "000100020AH",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640568612_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67200",
    product_id: 67200,
    title: "Двигатель",
    make: "Peugeot",
    model: "207",
    year: null,
    engine_code: "TU3A",
    engine_type: "unknown",
    price: 70000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "0135 LZ",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640554342_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67198",
    product_id: 67198,
    title: "Двигатель",
    make: "Nissan",
    model: "Pickup",
    year: null,
    engine_code: "KA24DE",
    engine_type: "unknown",
    price: 100000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640530953_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67196",
    product_id: 67196,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla",
    year: null,
    engine_code: "1ZZ-FE",
    engine_type: "unknown",
    price: 120000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "1900022A40",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/17664050204_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67194",
    product_id: 67194,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla Rumion",
    year: null,
    engine_code: "2ZR-FE",
    engine_type: "unknown",
    price: 95000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "190000T040",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640476875_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67192",
    product_id: 67192,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla Rumion",
    year: null,
    engine_code: "2ZR-FE",
    engine_type: "unknown",
    price: 95000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "190000T040",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640443597_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67190",
    product_id: 67190,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "ASX",
    year: null,
    engine_code: "4B11",
    engine_type: "unknown",
    price: 75000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "1000C726, 1000C837",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640395565_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67188",
    product_id: 67188,
    title: "Двигатель",
    make: "Volvo",
    model: "S80",
    year: null,
    engine_code: "B4204T6",
    engine_type: "unknown",
    price: 85000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "36001879, 36001988, ...",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640357881_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67186",
    product_id: 67186,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "Lancer",
    year: null,
    engine_code: "4B10",
    engine_type: "unknown",
    price: 100000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640300669_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67184",
    product_id: 67184,
    title: "Двигатель",
    make: "Toyota",
    model: "Camry",
    year: null,
    engine_code: "2AZ-FE",
    engine_type: "unknown",
    price: 100000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "190000H140",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/17664027361_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67182",
    product_id: 67182,
    title: "Двигатель",
    make: "Nissan",
    model: "Tiida",
    year: null,
    engine_code: "HR16DE",
    engine_type: "unknown",
    price: 40000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "101021PW2F",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176640243234_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67180",
    product_id: 67180,
    title: "Двигатель",
    make: "Subaru",
    model: "Legacy",
    year: null,
    engine_code: "EJ253",
    engine_type: "unknown",
    price: 55000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "10100BT760",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639730312_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67178",
    product_id: 67178,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla Rumion",
    year: null,
    engine_code: "2ZR-FE",
    engine_type: "unknown",
    price: 95000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "190000T040",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639708583_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67176",
    product_id: 67176,
    title: "Двигатель",
    make: "Peugeot",
    model: "4008",
    year: null,
    engine_code: "4B11",
    engine_type: "unknown",
    price: 75000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639586187_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67174",
    product_id: 67174,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "Outlander",
    year: null,
    engine_code: "4B12",
    engine_type: "unknown",
    price: 75000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "1000B575, 1000C854",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639550314_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67172",
    product_id: 67172,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla",
    year: null,
    engine_code: "1ZZ-FE",
    engine_type: "unknown",
    price: 120000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "1900022A40",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639524548_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67170",
    product_id: 67170,
    title: "Двигатель",
    make: "Suzuki",
    model: "Swift",
    year: null,
    engine_code: "M15A",
    engine_type: "unknown",
    price: 60000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "2000962JE2",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639471761_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67168",
    product_id: 67168,
    title: "Двигатель",
    make: "Suzuki",
    model: "Swift",
    year: null,
    engine_code: "M15A",
    engine_type: "unknown",
    price: 60000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639452515_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67166",
    product_id: 67166,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla",
    year: null,
    engine_code: "1ZZ-FE",
    engine_type: "unknown",
    price: 120000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "1900022A40",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639414685_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67164",
    product_id: 67164,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "ASX",
    year: null,
    engine_code: "4B11",
    engine_type: "unknown",
    price: 75000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "1000C726, 1000C837",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639364878_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67162",
    product_id: 67162,
    title: "Двигатель",
    make: "Nissan",
    model: "X-Trail",
    year: null,
    engine_code: "QR25DE",
    engine_type: "unknown",
    price: 80000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "10102JG3AC",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639294385_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67160",
    product_id: 67160,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "ASX",
    year: null,
    engine_code: "4B11",
    engine_type: "unknown",
    price: 75000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "1000B379, 1000C837",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176620273677_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67158",
    product_id: 67158,
    title: "Двигатель",
    make: "Nissan",
    model: "X-Trail",
    year: null,
    engine_code: "QR25DE",
    engine_type: "unknown",
    price: 80000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "10102JG3AC",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639204652_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67156",
    product_id: 67156,
    title: "Двигатель",
    make: "Toyota",
    model: "RAV4",
    year: null,
    engine_code: "1AZ-FE",
    engine_type: "unknown",
    price: 130000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "190000H150",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639170524_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67154",
    product_id: 67154,
    title: "Двигатель",
    make: "Suzuki",
    model: "Swift",
    year: null,
    engine_code: "M15A",
    engine_type: "unknown",
    price: 60000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639138571_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67152",
    product_id: 67152,
    title: "Двигатель",
    make: "Chevrolet",
    model: "Lacetti",
    year: null,
    engine_code: "T18SED",
    engine_type: "unknown",
    price: 100000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639074832_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67150",
    product_id: 67150,
    title: "Двигатель",
    make: "Nissan",
    model: "Tiida",
    year: null,
    engine_code: "HR16DE",
    engine_type: "unknown",
    price: 40000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "101021PW2F",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176639014425_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67148",
    product_id: 67148,
    title: "Двигатель",
    make: "Suzuki",
    model: "SX4",
    year: null,
    engine_code: "M16A",
    engine_type: "unknown",
    price: 55000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176638964373_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67146",
    product_id: 67146,
    title: "Двигатель",
    make: "Suzuki",
    model: "SX4",
    year: null,
    engine_code: "M16A",
    engine_type: "unknown",
    price: 55000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176638951434_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67144",
    product_id: 67144,
    title: "Двигатель",
    make: "Nissan",
    model: "Qashqai",
    year: null,
    engine_code: "MR20DE",
    engine_type: "unknown",
    price: 40000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "10102JE30F",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176638892431_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67142",
    product_id: 67142,
    title: "Двигатель",
    make: "Nissan",
    model: "Qashqai",
    year: null,
    engine_code: "MR20DE",
    engine_type: "unknown",
    price: 55000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "10102JE30F",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176638864160_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67140",
    product_id: 67140,
    title: "Двигатель",
    make: "Nissan",
    model: "Qashqai",
    year: null,
    engine_code: "MR20DE",
    engine_type: "unknown",
    price: 55000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "10102JN30F",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176638829999_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67138",
    product_id: 67138,
    title: "Двигатель",
    make: "Suzuki",
    model: "SX4",
    year: null,
    engine_code: "M16A",
    engine_type: "unknown",
    price: 55000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/17663814223_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67136",
    product_id: 67136,
    title: "Двигатель",
    make: "Nissan",
    model: "Qashqai",
    year: null,
    engine_code: "MR20DE",
    engine_type: "unknown",
    price: 40000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "10102JN30F",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176638098794_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67134",
    product_id: 67134,
    title: "Двигатель",
    make: "Toyota",
    model: "RAV4",
    year: null,
    engine_code: "1AZ-FE",
    engine_type: "unknown",
    price: 130000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "190000H150",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176638072058_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67133",
    product_id: 67133,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla",
    year: null,
    engine_code: "1ZR-FE",
    engine_type: "unknown",
    price: 110000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "190000T030",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/17663799386_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67131",
    product_id: 67131,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla",
    year: null,
    engine_code: "1ZR-FE",
    engine_type: "unknown",
    price: 110000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "190000T030",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176637905021_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67129",
    product_id: 67129,
    title: "Двигатель",
    make: "Nissan",
    model: "X-Trail",
    year: null,
    engine_code: "QR25DE",
    engine_type: "unknown",
    price: 80000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "10102JG3AC",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/17663784792_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67128",
    product_id: 67128,
    title: "Двигатель",
    make: "Toyota",
    model: "Corolla",
    year: null,
    engine_code: "1ZR-FE",
    engine_type: "unknown",
    price: 110000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "190000T030",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176637796662_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67126",
    product_id: 67126,
    title: "Двигатель",
    make: "Toyota",
    model: "RAV4",
    year: null,
    engine_code: "1AZ-FE",
    engine_type: "unknown",
    price: 130000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "190000H150",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/17663773709_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67124",
    product_id: 67124,
    title: "Двигатель",
    make: "Suzuki",
    model: "SX4",
    year: null,
    engine_code: "M16A",
    engine_type: "unknown",
    price: 55000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176637581776_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67122",
    product_id: 67122,
    title: "Двигатель",
    make: "Chevrolet",
    model: "Rezzo",
    year: null,
    engine_code: "T20SED",
    engine_type: "unknown",
    price: 80000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176637487650_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67120",
    product_id: 67120,
    title: "Двигатель",
    make: "Chevrolet",
    model: "Lacetti",
    year: null,
    engine_code: "T18SED",
    engine_type: "unknown",
    price: 100000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176620714498_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67118",
    product_id: 67118,
    title: "Двигатель",
    make: "Hyundai",
    model: "Solaris",
    year: null,
    engine_code: "G4FA",
    engine_type: "unknown",
    price: 75000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "211012BB14",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176620628399_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67117",
    product_id: 67117,
    title: "Двигатель",
    make: "Peugeot",
    model: "207",
    year: null,
    engine_code: "TU3A",
    engine_type: "unknown",
    price: 70000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "0135 LZ",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176620369473_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67115",
    product_id: 67115,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "Outlander",
    year: null,
    engine_code: "6B31",
    engine_type: "unknown",
    price: 190000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "1000A820, 1000C880",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176620303593_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67113",
    product_id: 67113,
    title: "Двигатель",
    make: "Mitsubishi",
    model: "ASX",
    year: null,
    engine_code: "4B11",
    engine_type: "unknown",
    price: 75000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: "1000C837, 1000B379",
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/17662027521_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
  {
    source: "mysakura",
    source_url: "https://mysakura.ru/product/67112",
    product_id: 67112,
    title: "Двигатель",
    make: "Daihatsu",
    model: "Terios",
    year: null,
    engine_code: "K3-VE",
    engine_type: "unknown",
    price: 100000,
    currency: "RUB",
    stock_text: "В наличии",
    oem: null,
    description: null,
    images: [
      "https://storage.yandexcloud.net/mysakura/176612249094_p470.jpg?response-content-type=image%2Fjpg&response-cache-control=public%2C+max-age%3D31536000",
    ],
  },
];
